### PR TITLE
adds new gpt-4 128k preview model

### PR DESCRIPTION
**Pull request by ghgoodreau**
## Motivation

New preview model with a massively improved context window will greatly increase the utility of Flux. 

## Solution

Just adds the gpt-4-1106-preview model to the list of options to select.

## Checklist

- [x] Tested in Chrome
- [x] Tested in Safari

### CODE REVIEW

**Comment by ghgoodreau** [comment]
@transmissions11 easy one. back on the grind 🫡

**Comment by transmissions11** [comment]
haha nice, but wait does this constant even matter anymore?

i think we have code that updates the array with all the models pulled from the api after loading

Screenshot 2023-11-06 at 1 18 05 PM

**Comment by transmissions11** [comment]
yeah i think ur a bit confused cuz your upstream is out of date, if u resolve the conflicts u'll we don't even have this array in here anymore

**Comment by ghgoodreau** [comment]
lmao oops, think i pulled the wrong branch

**Pull request closed without merging**
