### PR TITLE
feat: add support for other base urls, gpt 16k

### LINKED ISSUE #82: feat:  Local Model Compatibility
**Is your feature request related to a problem? Please describe.**
Limiting this to OpenAI is severely hampering its capabilities

**Describe the solution you'd like**
I want to run this hooked up to local LLMs, and can assume their output is similar in format to OpenAI's API.

### PR DESCRIPTION
**Pull request by alexkreidler**
## Motivation

This allows people to use OpenAI-compatible models like [LocalAI](https://github.com/go-skynet/LocalAI), and closes #82. Or it allows people to use their own openai proxy for api key safety or observability, or LLMOps products like [Helicone](https://docs.helicone.ai/quickstart/integrate-in-one-minute) or [Portkey](https://github.com/Portkey-AI/docs/blob/main/quickstart.md) (although these services need you to pass additional headers; maybe that's the next thing to add).

## Solution

Adds an API Base URL field to the settings page. I removed the API key modal because it seemed like duplicating functionality that's already in the settings modal. I do get the argument for simplicity, so maybe we could rework the settings modal UI e.g. hide extra options under a dropdown. I also put both the API key and base URL state in the same settings localStorage JSON object. I updated `openai-streams` package to fix typescript errors on the `apiBase` property. Also added a few missing dependencies that caused `pnpm` to fail.

## Checklist

- [x] Tested in Chrome
- [ ] Tested in Safari

### CODE REVIEW

**Comment by transmissions11** [comment]
> I removed the API key modal because it seemed like duplicating functionality that's already in the settings modal.

i felt the API key modal was important for the first time users interact w/ the app as otherwise they have no idea they need to enter anything and will just be annoyed their requests are failing?

**Comment by alexkreidler** [comment]
I have the settings modal open when no API key is set so that first time users are prompted to put in their info.

I'll get rid of the pnpm lockfile and try to fix the build (although I don't have access to the Vercel build logs). `npm run build` works fine on my machine, maybe it's just that lockfile?

**Comment by transmissions11** [comment]
whoops my bad didn't know you couldn't see logs, here ya go:

Screenshot 2023-06-15 at 6 27 39 AM

**Comment by alexkreidler** [comment]
@transmissions11 I've fixed the build and merged. I'd be happy to make any other changes- I think this will be a great feature to have on flux.paradigm.xyz!

**Comment by transmissions11** [comment]
can you add the api key modal back as well

**Pull request closed without merging**
